# Homework 1 - Exercise 2

### Name : Emma Parois

In [1]:
import numpy as np


In [2]:
def display_pattern(pattern):
    for i in pattern:
        for j in i:
            if j==1:
                print("1", end="")
            else:
                print(" ", end="")
        print(" ")
        

In [3]:
def sign(x):
    return 1*(x >= 0) - 1*(x < 0)


In [4]:
class HopfiedlNetwork:
    
    def __init__(self, p, N):
        self.p = p
        self.N = N
        self.U = np.zeros((N, p))
        self.x = np.zeros(N)
        self.W = np.zeros((N, N))
        self.S = np.zeros((N, p))
        
    def store_pattern(self, U):
        self.U = U
    
    def feed_pattern(self, x):
        self.S = x.flatten()
        self.x = x
    
    def retrieve_undistorted_pattern(self, nb_iterations):
        self.W = 1/self.N * self.U @ self.U.T
        np.fill_diagonal(self.W, 0)
        temp =  np.zeros(self.S.shape)
        i = 0
        while i != nb_iterations: 
            self._update_rule()
            temp = self.S  
            i += 1
        return self.S.reshape(self.x.shape)
    
    def _update_rule(self):
        for i in range(self.S.shape[0]):
            self.S[i] = sign(self.W[i,:] @ self.S)
        

In [5]:
x1 = np.array([ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1] ]) 

In [6]:
x2 = np.array([ [ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1] ])

In [7]:
x3 = np.array([ [ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1] ])

In [8]:
x4 = np.array([ [ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1] ])

In [9]:
x5 = np.array([ [ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, 1, 1, 1, 1, 1, 1, -1],[ -1, 1, 1, 1, 1, 1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1] ])

In [10]:
p = 5


In [11]:
N = x1.shape[0]*x1.shape[1]


In [12]:
U = np.array([x1.flatten(), x2.flatten(), x3.flatten(), x4.flatten(), x5.flatten()]).T


In [13]:
nb_iterations = 1000


## Question 1A

In [14]:
x = np.array([[1, -1, -1, -1, -1, 1, -1, -1, -1, -1], [1, -1, -1, 1, 1, -1, 1, -1, -1, -1], [1, -1, 1, 1, 1, -1, 1, 1, -1, -1], [1, 1, 1, 1, -1, 1, 1, 1, 1, -1], [1, 1, 1, 1, -1, 1, 1, 1, 1, -1], [1, 1, 1, 1, -1, 1, 1, 1, 1, -1], [1, 1, 1, 1, -1, 1, 1, 1, 1, -1], [1, 1, 1, 1, -1, 1, 1, 1, 1, -1], [1, 1, 1, 1, -1, 1, 1, 1, 1, -1], [1, 1, 1, 1, -1, 1, 1, 1, 1, -1], [1, 1, 1, 1, -1, 1, 1, 1, 1, -1], [1, 1, 1, 1, -1, 1, 1, 1, 1, -1], [1, 1, 1, 1, -1, 1, 1, 1, 1, -1], [1, -1, 1, 1, 1, -1, 1, 1, -1, -1], [1, -1, -1, 1, 1, -1, 1, -1, -1, -1], [1, -1, -1, -1, -1, 1, -1, -1, -1, -1]] )

In [15]:
net = HopfiedlNetwork(p, N)
net.store_pattern(U)
net.feed_pattern(x)
undist_pattern = net.retrieve_undistorted_pattern(nb_iterations)


In [16]:
undist_pattern


array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1,  1,  1,  1,  1,  1,  1, -1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1, -1,  1,  1,  1, -1],
       [-1, -1,  1,  1,  1,  1,  1,  1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [17]:
display_pattern(x)


1    1     
1  11 1    
1 111 11   
1111 1111  
1111 1111  
1111 1111  
1111 1111  
1111 1111  
1111 1111  
1111 1111  
1111 1111  
1111 1111  
1111 1111  
1 111 11   
1  11 1    
1    1     


In [18]:
display_pattern(undist_pattern)


           
   1111    
  111111   
 111  111  
 111  111  
 111  111  
 111  111  
 111  111  
 111  111  
 111  111  
 111  111  
 111  111  
 111  111  
  111111   
   1111    
           


## Question 2A

In [19]:
x = np.array([[-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1], [1, 1, 1, -1, -1, -1, -1, 1, 1, 1]] )

In [20]:
net = HopfiedlNetwork(p, N)
net.store_pattern(U)
net.feed_pattern(x)
undist_pattern = net.retrieve_undistorted_pattern(nb_iterations)


In [21]:
undist_pattern


array([[-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1],
       [-1, -1, -1,  1,  1,  1,  1, -1, -1, -1]])

In [22]:
display_pattern(x)


   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
111    111 


In [23]:
display_pattern(undist_pattern)


   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    
   1111    


## Question 3A

In [24]:
x = np.array([[1, -1, 1, 1, -1, -1, -1, -1, 1, 1], [-1, 1, 1, 1, -1, 1, -1, -1, 1, -1], [-1, 1, -1, -1, -1, 1, -1, 1, -1, 1], [-1, 1, -1, 1, -1, 1, 1, 1, -1, 1], [-1, 1, 1, 1, 1, -1, -1, -1, 1, 1], [1, -1, 1, 1, -1, -1, -1, 1, -1, 1], [1, -1, -1, -1, 1, 1, -1, -1, -1, 1], [1, -1, -1, 1, 1, -1, -1, 1, -1, 1], [1, -1, -1, 1, 1, 1, -1, -1, 1, 1], [1, 1, 1, -1, 1, -1, -1, 1, -1, 1], [1, -1, 1, -1, 1, -1, 1, -1, 1, -1], [1, -1, 1, -1, -1, 1, -1, 1, -1, -1], [1, 1, -1, -1, -1, -1, 1, 1, -1, 1], [-1, 1, -1, -1, -1, 1, -1, 1, -1, 1], [-1, -1, -1, -1, -1, 1, 1, -1, 1, -1], [1, -1, -1, 1, -1, 1, -1, -1, -1, -1]] )

In [25]:
net = HopfiedlNetwork(p, N)
net.store_pattern(U)
net.feed_pattern(x)
undist_pattern = net.retrieve_undistorted_pattern(nb_iterations)


In [26]:
undist_pattern


array([[ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1, -1, -1, -1,  1,  1],
       [ 1,  1, -1, -1, -1, -1, -1, -1,  1,  1],
       [ 1,  1, -1, -1, -1, -1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1,  1, -1,  1,  1,  1],
       [ 1,  1,  1, -1,  1,  1, -1,  1,  1,  1],
       [ 1,  1,  1, -1,  1,  1, -1,  1,  1,  1],
       [ 1,  1,  1, -1,  1,  1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1, -1, -1,  1,  1,  1]])

In [27]:
display_pattern(x)


1 11    11 
 111 1  1  
 1   1 1 1 
 1 1 111 1 
 1111   11 
1 11   1 1 
1   11   1 
1  11  1 1 
1  111  11 
111 1  1 1 
1 1 1 1 1  
1 1  1 1   
11    11 1 
 1   1 1 1 
     11 1  
1  1 1     


In [28]:
display_pattern(undist_pattern)


111    111 
111    111 
111     11 
111 1   11 
111 1   11 
111 1   11 
111 1   11 
11      11 
11      11 
111 11 111 
111 11 111 
111 11 111 
111 11 111 
111    111 
111    111 
111    111 
